[workspace]
members = ["application/server", "application/containers", "application/auth_module", "application/client", "application/task", "application/api"]
resolver = "2"

[profile.release-lto]
inherits = "release"
lto = true
codegen-units = 1
