[workspace]
members = ["application/grpc-proto", "application/server", "application/containers", "application/auth_module", "application/client", "application/task"]
resolver = "2"

[profile.release-lto]
inherits = "release"
lto = true
codegen-units = 1
