[package]
name = "web-packer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hyper = "0.14.20"
axum = "0.5.15"
mime_guess = "2.0.4"
mime = "0.3.16"
