env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:solid/typescript
overrides:
  - files: [ "build.js" ]
    env:
      node: true

parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - '@typescript-eslint'
  - 'solid'
rules: {
  no-mixed-spaces-and-tabs: off
}
