[package]
name = "web-frontend"
version = "0.1.0"
edition = "2021"

[dependencies]
web-packer = { path = "../web-packer" }
axum = "0.5.15"

[build-dependencies]
web-packer = { path = "../web-packer" }
