name: Protoc
description: Install protoc and update PATH
runs:
  using: "composite"
  steps:
    - name: cache windows protoc
      id: cache-windows-protoc
      if: runner.os == 'Windows'
      uses: actions/cache@v3
      with:
        path: ~/protobuf-compiler/protoc
        key: ${{ runner.os }}-protoc
    - id: protoc-path
      run: |
        New-Item -ItemType Directory -Path ~/protobuf-compiler -Force
        echo ("path=" + (Resolve-Path ~/protobuf-compiler).ToString()) >> $env:GITHUB_OUTPUT
      if: (runner.os == 'Windows')
      shell: pwsh
    - id: Windows
      run: |
        Invoke-WebRequest https://github.com/protocolbuffers/protobuf/releases/download/v21.8/protoc-21.8-win64.zip -OutFile protoc.zip
        Expand-Archive protoc.zip -DestinationPath protoc
      if: (runner.os == 'Windows') && (steps.cache-windows-protoc.outputs.cache-hit != 'true')
      working-directory: ${{ steps.protoc-path.outputs.path }}
      shell: pwsh
    - name: set windows path
      run: |
        echo (((Get-Location).ToString() + "\protoc\bin") -replace "\\", "/") >> $env:GITHUB_PATH
        ls -Recurse
        echo Path: ((Get-Location).ToString() + "\protoc\bin")
      if: (runner.os == 'Windows')
      working-directory: ${{ steps.protoc-path.outputs.path }}
      shell: pwsh
    - id: Linux
      run: sudo apt-get update -yqq && sudo apt-get install -yqq protobuf-compiler
      if: runner.os == 'Linux'
      shell: bash
    - name: check protoc
      run: protoc --version
      shell: bash