name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - uses: ./.github/actions/protoc
    - name: check protoc
      run: protoc --version
    - name: Cache build
      uses: actions/cache@v3
      with:
        path: target
        key: ${{ runner.os }}-build-debug
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

  build-release:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
    - uses: ./.github/actions/protoc
    - name: check protoc
      run: protoc --version
    - name: Cache build
      uses: actions/cache@v3
      with:
        path: target
        key: ${{ runner.os }}-build-optimized
    - name: Build
      run: cargo +nightly build --profile=release-lto --bins -Z unstable-options --out-dir binaries --verbose
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: build optimized
        path: binaries
        retention-days: 30
