name: Rust
run-name: Build and test @${{ github.sha }}

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/cargo
    - uses: ./.github/actions/protoc
    - name: Cache build
      uses: actions/cache@v3
      with:
        path: target
        key: ${{ runner.os }}-build-debug
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test -- --format=json -Z unstable-options --report-time | junitify -r --out ./tests/
    - name: JUnit Report Action
      uses: mikepenz/action-junit-report@v3
      if: always()
      with:
        report_paths: ./tests/*.xml



  build-release:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/cargo
    - uses: ./.github/actions/protoc
    - name: Cache build
      uses: actions/cache@v3
      with:
        path: target
        key: ${{ runner.os }}-build-optimized
    - name: Build
      run: cargo +nightly build --profile=release-lto --bins -Z unstable-options --out-dir binaries --verbose
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: build_optimized-${{ runner.os }}
        path: binaries
        retention-days: 30
